Загрузка файлов без считывания стрима на этапе биндинга модели
Byndyusoft/Byndyusoft.AspNetCore.Mvc.ModelBinding pull request #2
Opened 2023-07-26 12:13 UTC by Rinatich

2023-08-14 05:32 UTC, Alex-Grigorichev commented on README.md
> +## Requirements
Давай тогда отдельно создадим Requirements по установке пакета, а отдельный по использованию пакета?

2023-08-14 05:34 UTC, Alex-Grigorichev commented on README.md
>  ## Package development lifecycle
(Комментарий к строчке 125)
Добавь версию .net

2023-08-14 05:37 UTC, Alex-Grigorichev commented on README.md
> +3. Small - API receives 1 1Gb-sized generated files.
Large*

2023-08-14 05:52 UTC, Rinatich commented on README.md
> +## Requirements
Назвал по-другому

2023-08-14 05:52 UTC, Rinatich commented on README.md
>  ## Package development lifecycle
++

2023-08-14 05:52 UTC, Rinatich commented on README.md
> +3. Small - API receives 1 1Gb-sized generated files.
++

2023-08-14 07:52 UTC, Alex-Grigorichev requested changes

2023-08-14 07:52 UTC, Alex-Grigorichev commented on tests/PerformanceTests/Files/FileGenerator.cs
> +            {
либо удалить { } внутри foreach, либо в if добавить, выглядит неоднородно

2023-08-14 07:52 UTC, Alex-Grigorichev commented on tests/PerformanceTests/Files/FileGenerator.cs
> +            byte[] data = new byte[sizeInMb * bytesInMb];
var?

2023-08-14 07:52 UTC, Alex-Grigorichev commented on tests/TestApi/Startup.cs
> +            services.AddSwaggerGen();
Так ли нам нужен Swagger в API, который используется для тестирования?

2023-08-15 05:05 UTC, Rinatich commented on tests/PerformanceTests/Files/FileGenerator.cs
> +            {
Я убираю скобки, если выражение далее занимает одну строчку. У if одна строчка, у foreach - нет

2023-08-15 05:06 UTC, Rinatich commented on tests/PerformanceTests/Files/FileGenerator.cs
> +            byte[] data = new byte[sizeInMb * bytesInMb];
++

2023-08-15 05:06 UTC, Rinatich commented on tests/TestApi/Startup.cs
> +            services.AddSwaggerGen();
Я тестировал, что сваггер не работает. Нужен был.

2023-08-15 05:38 UTC, Alex-Grigorichev approved these changes

2023-08-15 09:34 UTC, artisna commented on README.md
> +In [Benchmarking](README.md#Benchmarking) section you can see that new behaviour is faster in high performance stream processing use cases. It is strongly recommened to measure performance for your u
recommened -> recommenDed

2023-08-16 14:11 UTC, Satem commented on README.md
> +This package allows you to read form data values and files. Files streams are not read in binding model process and are provided to be used in user code.
"Files streams are not read in binding model process and are provided to be used in user code." - скажи, пожалуйста, что это должно значить?

2023-08-16 14:15 UTC, Satem commented
Предлагаю в readme, комментариях и других текстах, которые может человек прочитать, использовать заглавные буквы для выделения терминов и названий: Form Data, ASP .NET Core и подобное.

2023-08-17 12:16 UTC, Rinatich commented on README.md
> +This package allows you to read form data values and files. Files streams are not read in binding model process and are provided to be used in user code.
Это означает: стримы файлов не считываются во время процессы привязки модели, а передаются на откуп пользователю, чтобы он считал их в коде

2023-08-17 12:17 UTC, Rinatich commented on README.md
> +In [Benchmarking](README.md#Benchmarking) section you can see that new behaviour is faster in high performance stream processing use cases. It is strongly recommened to measure performance for your u
++

2023-11-03 07:35 UTC, merged